### ISSUE TITLE
Better Social Menu support relying on Jetpack

### ISSUE THREAD

**Issue by Robertght** [pixelgrade/patch#188]
Ca la Gema: https://github.com/pixelgrade/gema/commit/7e7a71566e072c010feef9c7a3da8b9c53216971

Ref: https://secure.helpscout.net/conversation/344476221/662/?folderId=1142153

**Comment by georgeolaru** [comment]
Hai sa o lasam balta cu asta – nu cred ca e mai buna solutia din Jetpack.
