### ISSUE TITLE
[Mobile] Limit larger "Site Title" font size to overlap and cause horizontal scrolling

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/patch#222]
Au apărut câteva cazuri legate de un extra spațiu pe mobile când faci swipe dreapta. Am descoperit că problema ar putea veni de la opțiunea din Customizing ▸ Theme Options
Header ▸ Logo Height, dacă setezi height-ul peste 50px, atunci se va crea acel extra spațiu pe varianta de mobile. Cred că acest issue are legatura cu cel de aici: https://github.com/pixelgrade/patch/issues/193.

Screenshot:

-  https://cl.ly/9f89dd205b1f

Video:

-  Așa se vede pe Chrome desktop/mobile: https://cl.ly/4b3f71909ebb

Video:
 

- Așa se vede pe mobile ( Android ): https://cl.ly/33ce5149c786

Quick fix: 

```
.site-title {
    font-size: 18px;
}
```

**Comment by georgeolaru** [comment]
Din ce am testat, scroll-ul orizontal e cauzat de `font-size-ul` aplicat pe textul din `.site-title` – div ascuns atunci cand este folosita o imagine ca logo (ca in demo).

![image](https://user-images.githubusercontent.com/1632775/66466531-8a1cae80-ea8b-11e9-8043-4868d6cd7cac.png)

Propun ca abordam issue-ul din 2 perspective:
1. Sa gasim o alta modalitate de a ascunde titlul text (acum e cu `absolute` + `clip`)
2. Sa folosim o abordare gen `fit-text` pentru a nu permite titlului sa iasa in afara containerului (atunci cand e pus ca `font-size: 150px`; dar totusi sa se redimensioneze pentru cuvintele lungi astfel incat sa incapa in container.

**Resurse:**
   - https://twitter.com/sindresorhus/status/979363460411609091
   - https://github.com/rikschennink/fitty

**Comment by madalingorbanescu** [comment]
Propunerea mea ar fi sa nu aplicam valoarea din optiunea Logo Height, ca font size pe site title. Site title si logo-ul sunt 2 componente diferite si asa trebuie tratate.

Nu vad de ce am pune acel font-size: 150px, dar totusi sa il limitam in functie de lungimea cuvintelor.

@georgeolaru ce zici, scoatem acel font size de pe site title?

**Comment by georgeolaru** [comment]
@madalingorbanescu Inteleg rationamentul – inainte sa implementam sugestia am cateva intrebari:
1. Ce se intampla cu clientii actuali care folosesc optiunea cu "font-size"? Astazi ea e folosita de cei care nu folosesc o imagine pentru logo.
2. Ce dimensiune setam ca font-size default?

Ideal ar fi fost sa avem un "max-font-size" echivalent cu "max-height-ul" de la imagine.
