### ISSUE TITLE
[Mobile] Youtube Video not being responsive in Single Post

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/patch#232]
S-a rezolvat problema cu responsive video intr-un [update recent](https://github.com/pixelgrade/patch/issues/215), insa am omis atunci problema cu video **Youtube pe Single Post**, care inca nu e responsive.

**Comment by madalingorbanescu** [comment]
@alinclamba eu am testat cu block-ul de Youtube si e responsive. Poti sa mai testezi si tu o data cu ultima versiune a temei?

**Comment by alinclamba** [comment]
@madalingorbanescu așa e, am testat și eu acum încă o dată cu ultima versiune și problema nu mai e validă. Se poate închide în cazul ăsta. Mulțumesc. 🙏

**Comment by alinclamba** [comment]
Aici din păcate ne-a scăpat ceva — problema nu mai apare când folosești Gutenberg, e adevărat, dar apare când nu folosești Gutenberg. Se poate vedea inclusiv pe demo, [aici](https://demos.pixelgrade.com/patch/bikes/babes-ride-out-a-motorcycle-story/).

**Comment by alinclamba** [comment]
M-am enervat cu asta, așa că am investigat puțin treaba și am găsit _problema_. Pe demo,  la postarea cu pricina (de care s-a luat, de altfel, și un client de câteva ori), noi folosim metoda _veche_ de a plasa un video, prin embed iframe. Am pus link-ul de Youtube direct, și problema a dispărut. Deci, alarmă falsă, scuze de deranj. Închid și am terminat cu asta.
